# This file is automatically generated by pyo3_stub_gen

import collections.abc
import typing

__all__ = [
    "parse_args",
]

def parse_args(args: collections.abc.Sequence[str], columns: int | None = None) -> dict[str, typing.Any]: ...
