name: Build vsview-cli
on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.12"

jobs:
  wheels:
    name: Build wheels (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0

      - name: Set up uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          enable-cache: true

      - name: Build sdist
        if: matrix.os == 'macos-latest'
        run: uv build --package vsview-cli --sdist --out-dir dist --clear

      - name: Upload sdist
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: sdist
          path: dist/*.tar.gz

      - name: Build wheels
        uses: pypa/cibuildwheel@294735312765b09d24a2fbec22660ce817587d55 # v4.1
        with:
          package-dir: src/vsview-cli
          output-dir: wheelhouse

      - name: Upload wheels
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: wheels-${{ matrix.os }}
          path: wheelhouse/*.whl
